# SPDX-License-Identifier: GPL-2.0
# Makefile for Linux samples code

obj-$(CONFIG_SAMPLE_ANDROID_BINDERFS)	+= binderfs/
obj-$(CONFIG_SAMPLE_CONFIGFS)		+= configfs/
obj-$(CONFIG_SAMPLE_CONNECTOR)		+= connector/
subdir-y				+= hidraw
obj-$(CONFIG_SAMPLE_HW_BREAKPOINT)	+= hw_breakpoint/
obj-$(CONFIG_SAMPLE_KDB)		+= kdb/
obj-$(CONFIG_SAMPLE_KFIFO)		+= kfifo/
obj-$(CONFIG_SAMPLE_KOBJECT)		+= kobject/
obj-$(CONFIG_SAMPLE_KPROBES)		+= kprobes/
obj-$(CONFIG_SAMPLE_LIVEPATCH)		+= livepatch/
obj-$(CONFIG_SAMPLE_QMI_CLIENT)		+= qmi/
obj-$(CONFIG_SAMPLE_RPMSG_CLIENT)	+= rpmsg/
subdir-$(CONFIG_SAMPLE_SECCOMP)		+= seccomp
subdir-$(CONFIG_SAMPLE_VFS)		+= vfs
obj-$(CONFIG_SAMPLE_TRACE_EVENTS)	+= trace_events/
obj-$(CONFIG_SAMPLE_TRACE_PRINTK)	+= trace_printk/
obj-$(CONFIG_VIDEO_PCI_SKELETON)	+= v4l/
obj-y					+= vfio-mdev/ pidfd/
